// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module copy_local_beta (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        beta_buffer_address0,
        beta_buffer_ce0,
        beta_buffer_q0,
        local_beta_buffer_0,
        local_beta_buffer_1,
        local_beta_buffer_2,
        local_beta_buffer_3,
        local_beta_buffer_4,
        local_beta_buffer_5,
        local_beta_buffer_6,
        local_beta_buffer_7,
        local_beta_buffer_8,
        local_beta_buffer_9,
        local_beta_buffer_10,
        local_beta_buffer_11,
        local_beta_buffer_12,
        local_beta_buffer_13,
        local_beta_buffer_14,
        local_beta_buffer_15,
        local_beta_buffer_16,
        local_beta_buffer_17,
        local_beta_buffer_18,
        local_beta_buffer_19,
        local_beta_buffer_20,
        local_beta_buffer_21,
        local_beta_buffer_22,
        local_beta_buffer_23,
        local_beta_buffer_24,
        local_beta_buffer_25,
        local_beta_buffer_26,
        local_beta_buffer_27,
        local_beta_buffer_28,
        local_beta_buffer_29,
        local_beta_buffer_30,
        local_beta_buffer_31,
        local_beta_buffer_32,
        local_beta_buffer_33,
        local_beta_buffer_34,
        local_beta_buffer_35,
        local_beta_buffer_36,
        local_beta_buffer_37,
        local_beta_buffer_38,
        local_beta_buffer_39,
        local_beta_buffer_40,
        local_beta_buffer_41,
        local_beta_buffer_42,
        local_beta_buffer_43,
        local_beta_buffer_44,
        local_beta_buffer_45,
        local_beta_buffer_46,
        local_beta_buffer_47,
        local_beta_buffer_48,
        local_beta_buffer_49,
        local_beta_buffer_50,
        local_beta_buffer_51,
        local_beta_buffer_52,
        local_beta_buffer_53,
        local_beta_buffer_54,
        local_beta_buffer_55,
        local_beta_buffer_56,
        local_beta_buffer_57,
        local_beta_buffer_58,
        local_beta_buffer_59,
        TM_MIN,
        m,
        InterSubBeta,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_return_32,
        ap_return_33,
        ap_return_34,
        ap_return_35,
        ap_return_36,
        ap_return_37,
        ap_return_38,
        ap_return_39,
        ap_return_40,
        ap_return_41,
        ap_return_42,
        ap_return_43,
        ap_return_44,
        ap_return_45,
        ap_return_46,
        ap_return_47,
        ap_return_48,
        ap_return_49,
        ap_return_50,
        ap_return_51,
        ap_return_52,
        ap_return_53,
        ap_return_54,
        ap_return_55,
        ap_return_56,
        ap_return_57,
        ap_return_58,
        ap_return_59
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] beta_buffer_address0;
output   beta_buffer_ce0;
input  [15:0] beta_buffer_q0;
input  [31:0] local_beta_buffer_0;
input  [31:0] local_beta_buffer_1;
input  [31:0] local_beta_buffer_2;
input  [31:0] local_beta_buffer_3;
input  [31:0] local_beta_buffer_4;
input  [31:0] local_beta_buffer_5;
input  [31:0] local_beta_buffer_6;
input  [31:0] local_beta_buffer_7;
input  [31:0] local_beta_buffer_8;
input  [31:0] local_beta_buffer_9;
input  [31:0] local_beta_buffer_10;
input  [31:0] local_beta_buffer_11;
input  [31:0] local_beta_buffer_12;
input  [31:0] local_beta_buffer_13;
input  [31:0] local_beta_buffer_14;
input  [31:0] local_beta_buffer_15;
input  [31:0] local_beta_buffer_16;
input  [31:0] local_beta_buffer_17;
input  [31:0] local_beta_buffer_18;
input  [31:0] local_beta_buffer_19;
input  [31:0] local_beta_buffer_20;
input  [31:0] local_beta_buffer_21;
input  [31:0] local_beta_buffer_22;
input  [31:0] local_beta_buffer_23;
input  [31:0] local_beta_buffer_24;
input  [31:0] local_beta_buffer_25;
input  [31:0] local_beta_buffer_26;
input  [31:0] local_beta_buffer_27;
input  [31:0] local_beta_buffer_28;
input  [31:0] local_beta_buffer_29;
input  [31:0] local_beta_buffer_30;
input  [31:0] local_beta_buffer_31;
input  [31:0] local_beta_buffer_32;
input  [31:0] local_beta_buffer_33;
input  [31:0] local_beta_buffer_34;
input  [31:0] local_beta_buffer_35;
input  [31:0] local_beta_buffer_36;
input  [31:0] local_beta_buffer_37;
input  [31:0] local_beta_buffer_38;
input  [31:0] local_beta_buffer_39;
input  [31:0] local_beta_buffer_40;
input  [31:0] local_beta_buffer_41;
input  [31:0] local_beta_buffer_42;
input  [31:0] local_beta_buffer_43;
input  [31:0] local_beta_buffer_44;
input  [31:0] local_beta_buffer_45;
input  [31:0] local_beta_buffer_46;
input  [31:0] local_beta_buffer_47;
input  [31:0] local_beta_buffer_48;
input  [31:0] local_beta_buffer_49;
input  [31:0] local_beta_buffer_50;
input  [31:0] local_beta_buffer_51;
input  [31:0] local_beta_buffer_52;
input  [31:0] local_beta_buffer_53;
input  [31:0] local_beta_buffer_54;
input  [31:0] local_beta_buffer_55;
input  [31:0] local_beta_buffer_56;
input  [31:0] local_beta_buffer_57;
input  [31:0] local_beta_buffer_58;
input  [31:0] local_beta_buffer_59;
input  [31:0] TM_MIN;
input  [31:0] m;
input  [31:0] InterSubBeta;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;
output  [31:0] ap_return_5;
output  [31:0] ap_return_6;
output  [31:0] ap_return_7;
output  [31:0] ap_return_8;
output  [31:0] ap_return_9;
output  [31:0] ap_return_10;
output  [31:0] ap_return_11;
output  [31:0] ap_return_12;
output  [31:0] ap_return_13;
output  [31:0] ap_return_14;
output  [31:0] ap_return_15;
output  [31:0] ap_return_16;
output  [31:0] ap_return_17;
output  [31:0] ap_return_18;
output  [31:0] ap_return_19;
output  [31:0] ap_return_20;
output  [31:0] ap_return_21;
output  [31:0] ap_return_22;
output  [31:0] ap_return_23;
output  [31:0] ap_return_24;
output  [31:0] ap_return_25;
output  [31:0] ap_return_26;
output  [31:0] ap_return_27;
output  [31:0] ap_return_28;
output  [31:0] ap_return_29;
output  [31:0] ap_return_30;
output  [31:0] ap_return_31;
output  [31:0] ap_return_32;
output  [31:0] ap_return_33;
output  [31:0] ap_return_34;
output  [31:0] ap_return_35;
output  [31:0] ap_return_36;
output  [31:0] ap_return_37;
output  [31:0] ap_return_38;
output  [31:0] ap_return_39;
output  [31:0] ap_return_40;
output  [31:0] ap_return_41;
output  [31:0] ap_return_42;
output  [31:0] ap_return_43;
output  [31:0] ap_return_44;
output  [31:0] ap_return_45;
output  [31:0] ap_return_46;
output  [31:0] ap_return_47;
output  [31:0] ap_return_48;
output  [31:0] ap_return_49;
output  [31:0] ap_return_50;
output  [31:0] ap_return_51;
output  [31:0] ap_return_52;
output  [31:0] ap_return_53;
output  [31:0] ap_return_54;
output  [31:0] ap_return_55;
output  [31:0] ap_return_56;
output  [31:0] ap_return_57;
output  [31:0] ap_return_58;
output  [31:0] ap_return_59;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg beta_buffer_ce0;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg  signed [31:0] offset_0_reg_1151;
reg   [15:0] tm_0_reg_1160;
wire   [0:0] icmp_ln369_fu_1475_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [15:0] tm_fu_1480_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [5:0] trunc_ln373_fu_1491_p1;
reg   [5:0] trunc_ln373_reg_4359;
wire   [31:0] offset_fu_1495_p2;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
wire  signed [63:0] sext_ln373_fu_1486_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] local_beta_buffer59_060_fu_280;
wire   [31:0] shl_ln373_fu_1505_p2;
wire    ap_CS_fsm_state4;
reg   [31:0] local_beta_buffer26_061_fu_284;
reg   [0:0] write_flag185_0_fu_288;
reg   [31:0] local_beta_buffer58_062_fu_292;
reg   [0:0] write_flag87_0_fu_296;
reg   [0:0] write_flag182_0_fu_300;
reg   [31:0] local_beta_buffer57_063_fu_304;
reg   [31:0] local_beta_buffer27_064_fu_308;
reg   [0:0] write_flag179_0_fu_312;
reg   [31:0] local_beta_buffer56_065_fu_316;
reg   [0:0] write_flag90_0_fu_320;
reg   [0:0] write_flag176_0_fu_324;
reg   [31:0] local_beta_buffer55_066_fu_328;
reg   [31:0] local_beta_buffer28_067_fu_332;
reg   [0:0] write_flag173_0_fu_336;
reg   [31:0] local_beta_buffer54_068_fu_340;
reg   [0:0] write_flag94_0_fu_344;
reg   [0:0] write_flag170_0_fu_348;
reg   [31:0] local_beta_buffer53_069_fu_352;
reg   [31:0] local_beta_buffer299_fu_356;
reg   [0:0] write_flag167_0_fu_360;
reg   [31:0] local_beta_buffer52_071_fu_364;
reg   [0:0] write_flag98_0_fu_368;
reg   [0:0] write_flag164_0_fu_372;
reg   [31:0] local_beta_buffer51_072_fu_376;
reg   [31:0] local_beta_buffer30_073_fu_380;
reg   [0:0] write_flag161_0_fu_384;
reg   [31:0] local_beta_buffer50_074_fu_388;
reg   [0:0] write_flag101_0_fu_392;
reg   [0:0] write_flag158_0_fu_396;
reg   [31:0] local_beta_buffer49_075_fu_400;
reg   [31:0] local_beta_buffer31_076_fu_404;
reg   [0:0] write_flag155_0_fu_408;
reg   [31:0] local_beta_buffer48_077_fu_412;
reg   [0:0] write_flag104_0_fu_416;
reg   [0:0] write_flag152_0_fu_420;
reg   [31:0] local_beta_buffer47_078_fu_424;
reg   [31:0] local_beta_buffer32_079_fu_428;
reg   [0:0] write_flag149_0_fu_432;
reg   [31:0] local_beta_buffer46_080_fu_436;
reg   [0:0] write_flag107_0_fu_440;
reg   [0:0] write_flag146_0_fu_444;
reg   [31:0] local_beta_buffer45_081_fu_448;
reg   [31:0] local_beta_buffer33_082_fu_452;
reg   [0:0] write_flag143_0_fu_456;
reg   [31:0] local_beta_buffer44_083_fu_460;
reg   [0:0] write_flag110_0_fu_464;
reg   [0:0] write_flag140_0_fu_468;
reg   [31:0] local_beta_buffer43_084_fu_472;
reg   [31:0] local_beta_buffer34_085_fu_476;
reg   [0:0] write_flag137_0_fu_480;
reg   [31:0] local_beta_buffer42_086_fu_484;
reg   [0:0] write_flag113_0_fu_488;
reg   [0:0] write_flag134_0_fu_492;
reg   [31:0] local_beta_buffer41_087_fu_496;
reg   [31:0] local_beta_buffer35_088_fu_500;
reg   [0:0] write_flag131_0_fu_504;
reg   [31:0] local_beta_buffer40_089_fu_508;
reg   [0:0] write_flag116_0_fu_512;
reg   [0:0] write_flag128_0_fu_516;
reg   [31:0] local_beta_buffer39_090_fu_520;
reg   [31:0] local_beta_buffer36_091_fu_524;
reg   [0:0] write_flag125_0_fu_528;
reg   [31:0] local_beta_buffer38_092_fu_532;
reg   [0:0] write_flag119_0_fu_536;
reg   [0:0] write_flag122_0_fu_540;
reg   [31:0] local_beta_buffer37_093_fu_544;
reg   [0:0] write_flag84_0_fu_548;
reg   [31:0] local_beta_buffer25_094_fu_552;
reg   [0:0] write_flag_0_fu_556;
reg   [0:0] write_flag81_0_fu_560;
reg   [31:0] local_beta_buffer24_095_fu_564;
reg   [31:0] local_beta_buffer_096_fu_568;
reg   [0:0] write_flag78_0_fu_572;
reg   [31:0] local_beta_buffer23_097_fu_576;
reg   [0:0] write_flag4_0_fu_580;
reg   [0:0] write_flag75_0_fu_584;
reg   [31:0] local_beta_buffer22_098_fu_588;
reg   [31:0] local_beta_buffer16_099_fu_592;
reg   [0:0] write_flag72_0_fu_596;
reg   [31:0] local_beta_buffer21_0100_fu_600;
reg   [0:0] write_flag8_0_fu_604;
reg   [0:0] write_flag69_0_fu_608;
reg   [31:0] local_beta_buffer20_0101_fu_612;
reg   [31:0] local_beta_buffer2_0102_fu_616;
reg   [0:0] write_flag66_0_fu_620;
reg   [31:0] local_beta_buffer19_0103_fu_624;
reg   [0:0] write_flag11_0_fu_628;
reg   [0:0] write_flag63_0_fu_632;
reg   [31:0] local_beta_buffer18_0104_fu_636;
reg   [31:0] local_beta_buffer3_0105_fu_640;
reg   [0:0] write_flag60_0_fu_644;
reg   [31:0] local_beta_buffer17_0106_fu_648;
reg   [0:0] write_flag14_0_fu_652;
reg   [0:0] write_flag57_0_fu_656;
reg   [31:0] local_beta_buffer165_fu_660;
reg   [31:0] local_beta_buffer4_0108_fu_664;
reg   [0:0] write_flag53_0_fu_668;
reg   [31:0] local_beta_buffer155_fu_672;
reg   [0:0] write_flag17_0_fu_676;
reg   [0:0] write_flag48_0_fu_680;
reg   [31:0] local_beta_buffer14_0110_fu_684;
reg   [31:0] local_beta_buffer5_0111_fu_688;
reg   [0:0] write_flag44_0_fu_692;
reg   [31:0] local_beta_buffer13_0112_fu_696;
reg   [0:0] write_flag20_0_fu_700;
reg   [0:0] write_flag41_0_fu_704;
reg   [31:0] local_beta_buffer12_0113_fu_708;
reg   [31:0] local_beta_buffer6_0114_fu_712;
reg   [0:0] write_flag38_0_fu_716;
reg   [31:0] local_beta_buffer11_0115_fu_720;
reg   [0:0] write_flag23_0_fu_724;
reg   [0:0] write_flag35_0_fu_728;
reg   [31:0] local_beta_buffer10_0116_fu_732;
reg   [31:0] local_beta_buffer7_0117_fu_736;
reg   [0:0] write_flag32_0_fu_740;
reg   [31:0] local_beta_buffer9_0118_fu_744;
reg   [0:0] write_flag26_0_fu_748;
reg   [0:0] write_flag29_0_fu_752;
reg   [31:0] local_beta_buffer8_0119_fu_756;
wire   [31:0] zext_ln369_fu_1471_p1;
wire  signed [31:0] sext_ln373_1_fu_1501_p1;
wire   [31:0] select_ln376_fu_2470_p3;
wire   [31:0] select_ln376_1_fu_2477_p3;
wire   [31:0] select_ln376_2_fu_2484_p3;
wire   [31:0] select_ln376_3_fu_2491_p3;
wire   [31:0] select_ln376_4_fu_2498_p3;
wire   [31:0] select_ln376_5_fu_2505_p3;
wire   [31:0] select_ln376_6_fu_2512_p3;
wire   [31:0] select_ln376_7_fu_2519_p3;
wire   [31:0] select_ln376_8_fu_2526_p3;
wire   [31:0] select_ln376_9_fu_2533_p3;
wire   [31:0] select_ln376_10_fu_2540_p3;
wire   [31:0] select_ln376_11_fu_2547_p3;
wire   [31:0] select_ln376_12_fu_2554_p3;
wire   [31:0] select_ln376_13_fu_2561_p3;
wire   [31:0] select_ln376_14_fu_2568_p3;
wire   [31:0] select_ln376_15_fu_2575_p3;
wire   [31:0] select_ln376_16_fu_2582_p3;
wire   [31:0] select_ln376_17_fu_2589_p3;
wire   [31:0] select_ln376_18_fu_2596_p3;
wire   [31:0] select_ln376_19_fu_2603_p3;
wire   [31:0] select_ln376_20_fu_2610_p3;
wire   [31:0] select_ln376_21_fu_2617_p3;
wire   [31:0] select_ln376_22_fu_2624_p3;
wire   [31:0] select_ln376_23_fu_2631_p3;
wire   [31:0] select_ln376_24_fu_2638_p3;
wire   [31:0] select_ln376_25_fu_2645_p3;
wire   [31:0] select_ln376_26_fu_2652_p3;
wire   [31:0] select_ln376_27_fu_2659_p3;
wire   [31:0] select_ln376_28_fu_2666_p3;
wire   [31:0] select_ln376_29_fu_2673_p3;
wire   [31:0] select_ln376_30_fu_2680_p3;
wire   [31:0] select_ln376_31_fu_2687_p3;
wire   [31:0] select_ln376_32_fu_2694_p3;
wire   [31:0] select_ln376_33_fu_2701_p3;
wire   [31:0] select_ln376_34_fu_2708_p3;
wire   [31:0] select_ln376_35_fu_2715_p3;
wire   [31:0] select_ln376_36_fu_2722_p3;
wire   [31:0] select_ln376_37_fu_2729_p3;
wire   [31:0] select_ln376_38_fu_2736_p3;
wire   [31:0] select_ln376_39_fu_2743_p3;
wire   [31:0] select_ln376_40_fu_2750_p3;
wire   [31:0] select_ln376_41_fu_2757_p3;
wire   [31:0] select_ln376_42_fu_2764_p3;
wire   [31:0] select_ln376_43_fu_2771_p3;
wire   [31:0] select_ln376_44_fu_2778_p3;
wire   [31:0] select_ln376_45_fu_2785_p3;
wire   [31:0] select_ln376_46_fu_2792_p3;
wire   [31:0] select_ln376_47_fu_2799_p3;
wire   [31:0] select_ln376_48_fu_2806_p3;
wire   [31:0] select_ln376_49_fu_2813_p3;
wire   [31:0] select_ln376_50_fu_2820_p3;
wire   [31:0] select_ln376_51_fu_2827_p3;
wire   [31:0] select_ln376_52_fu_2834_p3;
wire   [31:0] select_ln376_53_fu_2841_p3;
wire   [31:0] select_ln376_54_fu_2848_p3;
wire   [31:0] select_ln376_55_fu_2855_p3;
wire   [31:0] select_ln376_56_fu_2862_p3;
wire   [31:0] select_ln376_57_fu_2869_p3;
wire   [31:0] select_ln376_58_fu_2876_p3;
wire   [31:0] select_ln376_59_fu_2883_p3;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln369_fu_1475_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        offset_0_reg_1151 <= offset_fu_1495_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        offset_0_reg_1151 <= m;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln369_fu_1475_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tm_0_reg_1160 <= tm_fu_1480_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tm_0_reg_1160 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd31) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag101_0_fu_392 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag101_0_fu_392 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd32) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag104_0_fu_416 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag104_0_fu_416 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd33) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag107_0_fu_440 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag107_0_fu_440 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd34) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag110_0_fu_464 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag110_0_fu_464 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd35) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag113_0_fu_488 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag113_0_fu_488 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd36) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag116_0_fu_512 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag116_0_fu_512 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd37) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag119_0_fu_536 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag119_0_fu_536 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag11_0_fu_628 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag11_0_fu_628 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd38) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag122_0_fu_540 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag122_0_fu_540 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd39) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag125_0_fu_528 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag125_0_fu_528 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd40) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag128_0_fu_516 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag128_0_fu_516 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd41) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag131_0_fu_504 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag131_0_fu_504 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd42) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag134_0_fu_492 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag134_0_fu_492 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd43) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag137_0_fu_480 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag137_0_fu_480 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd44) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag140_0_fu_468 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag140_0_fu_468 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd45) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag143_0_fu_456 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag143_0_fu_456 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd46) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag146_0_fu_444 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag146_0_fu_444 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd47) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag149_0_fu_432 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag149_0_fu_432 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag14_0_fu_652 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag14_0_fu_652 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd48) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag152_0_fu_420 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag152_0_fu_420 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd49) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag155_0_fu_408 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag155_0_fu_408 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd50) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag158_0_fu_396 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag158_0_fu_396 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd51) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag161_0_fu_384 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag161_0_fu_384 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd52) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag164_0_fu_372 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag164_0_fu_372 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd53) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag167_0_fu_360 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag167_0_fu_360 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd54) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag170_0_fu_348 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag170_0_fu_348 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd55) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag173_0_fu_336 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag173_0_fu_336 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd56) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag176_0_fu_324 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag176_0_fu_324 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd57) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag179_0_fu_312 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag179_0_fu_312 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag17_0_fu_676 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag17_0_fu_676 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd58) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag182_0_fu_300 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag182_0_fu_300 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((trunc_ln373_reg_4359 == 6'd59) | ((trunc_ln373_reg_4359 == 6'd60) | ((trunc_ln373_reg_4359 == 6'd61) | ((trunc_ln373_reg_4359 == 6'd62) | (trunc_ln373_reg_4359 == 6'd63))))))) begin
        write_flag185_0_fu_288 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag185_0_fu_288 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag20_0_fu_700 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag20_0_fu_700 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag23_0_fu_724 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag23_0_fu_724 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag26_0_fu_748 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag26_0_fu_748 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag29_0_fu_752 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag29_0_fu_752 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag32_0_fu_740 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag32_0_fu_740 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd11) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag35_0_fu_728 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag35_0_fu_728 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd12) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag38_0_fu_716 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag38_0_fu_716 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag41_0_fu_704 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag41_0_fu_704 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd14) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag44_0_fu_692 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag44_0_fu_692 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd15) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag48_0_fu_680 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag48_0_fu_680 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag4_0_fu_580 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag4_0_fu_580 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd16) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag53_0_fu_668 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag53_0_fu_668 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd17) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag57_0_fu_656 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag57_0_fu_656 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd18) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag60_0_fu_644 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag60_0_fu_644 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd19) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag63_0_fu_632 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag63_0_fu_632 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd20) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag66_0_fu_620 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag66_0_fu_620 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd21) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag69_0_fu_608 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag69_0_fu_608 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd22) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag72_0_fu_596 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag72_0_fu_596 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd23) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag75_0_fu_584 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag75_0_fu_584 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd24) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag78_0_fu_572 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag78_0_fu_572 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd25) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag81_0_fu_560 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag81_0_fu_560 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd26) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag84_0_fu_548 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag84_0_fu_548 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd27) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag87_0_fu_296 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag87_0_fu_296 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag8_0_fu_604 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag8_0_fu_604 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd28) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag90_0_fu_320 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag90_0_fu_320 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd29) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag94_0_fu_344 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag94_0_fu_344 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd30) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag98_0_fu_368 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag98_0_fu_368 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_flag_0_fu_556 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag_0_fu_556 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer10_0116_fu_732 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd11) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer11_0115_fu_720 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd12) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer12_0113_fu_708 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer13_0112_fu_696 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd14) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer14_0110_fu_684 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd15) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer155_fu_672 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd16) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer165_fu_660 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer16_099_fu_592 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd17) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer17_0106_fu_648 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd18) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer18_0104_fu_636 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd19) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer19_0103_fu_624 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd20) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer20_0101_fu_612 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd21) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer21_0100_fu_600 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd22) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer22_098_fu_588 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd23) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer23_097_fu_576 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd24) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer24_095_fu_564 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd25) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer25_094_fu_552 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd26) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer26_061_fu_284 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd27) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer27_064_fu_308 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd28) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer28_067_fu_332 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd29) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer299_fu_356 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer2_0102_fu_616 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd30) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer30_073_fu_380 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd31) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer31_076_fu_404 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd32) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer32_079_fu_428 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd33) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer33_082_fu_452 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd34) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer34_085_fu_476 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd35) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer35_088_fu_500 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd36) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer36_091_fu_524 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd37) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer37_093_fu_544 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd38) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer38_092_fu_532 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd39) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer39_090_fu_520 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer3_0105_fu_640 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd40) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer40_089_fu_508 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd41) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer41_087_fu_496 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd42) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer42_086_fu_484 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd43) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer43_084_fu_472 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd44) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer44_083_fu_460 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd45) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer45_081_fu_448 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd46) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer46_080_fu_436 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd47) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer47_078_fu_424 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd48) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer48_077_fu_412 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd49) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer49_075_fu_400 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer4_0108_fu_664 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd50) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer50_074_fu_388 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd51) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer51_072_fu_376 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd52) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer52_071_fu_364 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd53) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer53_069_fu_352 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd54) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer54_068_fu_340 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd55) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer55_066_fu_328 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd56) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer56_065_fu_316 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd57) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer57_063_fu_304 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd58) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer58_062_fu_292 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((trunc_ln373_reg_4359 == 6'd59) | ((trunc_ln373_reg_4359 == 6'd60) | ((trunc_ln373_reg_4359 == 6'd61) | ((trunc_ln373_reg_4359 == 6'd62) | (trunc_ln373_reg_4359 == 6'd63))))))) begin
        local_beta_buffer59_060_fu_280 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer5_0111_fu_688 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer6_0114_fu_712 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer7_0117_fu_736 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer8_0119_fu_756 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer9_0118_fu_744 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln373_reg_4359 == 6'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_beta_buffer_096_fu_568 <= shl_ln373_fu_1505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln369_fu_1475_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln373_reg_4359 <= trunc_ln373_fu_1491_p1;
    end
end

always @ (*) begin
    if ((icmp_ln369_fu_1475_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        beta_buffer_ce0 = 1'b1;
    end else begin
        beta_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln369_fu_1475_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln369_fu_1475_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return_0 = select_ln376_fu_2470_p3;

assign ap_return_1 = select_ln376_1_fu_2477_p3;

assign ap_return_10 = select_ln376_10_fu_2540_p3;

assign ap_return_11 = select_ln376_11_fu_2547_p3;

assign ap_return_12 = select_ln376_12_fu_2554_p3;

assign ap_return_13 = select_ln376_13_fu_2561_p3;

assign ap_return_14 = select_ln376_14_fu_2568_p3;

assign ap_return_15 = select_ln376_15_fu_2575_p3;

assign ap_return_16 = select_ln376_16_fu_2582_p3;

assign ap_return_17 = select_ln376_17_fu_2589_p3;

assign ap_return_18 = select_ln376_18_fu_2596_p3;

assign ap_return_19 = select_ln376_19_fu_2603_p3;

assign ap_return_2 = select_ln376_2_fu_2484_p3;

assign ap_return_20 = select_ln376_20_fu_2610_p3;

assign ap_return_21 = select_ln376_21_fu_2617_p3;

assign ap_return_22 = select_ln376_22_fu_2624_p3;

assign ap_return_23 = select_ln376_23_fu_2631_p3;

assign ap_return_24 = select_ln376_24_fu_2638_p3;

assign ap_return_25 = select_ln376_25_fu_2645_p3;

assign ap_return_26 = select_ln376_26_fu_2652_p3;

assign ap_return_27 = select_ln376_27_fu_2659_p3;

assign ap_return_28 = select_ln376_28_fu_2666_p3;

assign ap_return_29 = select_ln376_29_fu_2673_p3;

assign ap_return_3 = select_ln376_3_fu_2491_p3;

assign ap_return_30 = select_ln376_30_fu_2680_p3;

assign ap_return_31 = select_ln376_31_fu_2687_p3;

assign ap_return_32 = select_ln376_32_fu_2694_p3;

assign ap_return_33 = select_ln376_33_fu_2701_p3;

assign ap_return_34 = select_ln376_34_fu_2708_p3;

assign ap_return_35 = select_ln376_35_fu_2715_p3;

assign ap_return_36 = select_ln376_36_fu_2722_p3;

assign ap_return_37 = select_ln376_37_fu_2729_p3;

assign ap_return_38 = select_ln376_38_fu_2736_p3;

assign ap_return_39 = select_ln376_39_fu_2743_p3;

assign ap_return_4 = select_ln376_4_fu_2498_p3;

assign ap_return_40 = select_ln376_40_fu_2750_p3;

assign ap_return_41 = select_ln376_41_fu_2757_p3;

assign ap_return_42 = select_ln376_42_fu_2764_p3;

assign ap_return_43 = select_ln376_43_fu_2771_p3;

assign ap_return_44 = select_ln376_44_fu_2778_p3;

assign ap_return_45 = select_ln376_45_fu_2785_p3;

assign ap_return_46 = select_ln376_46_fu_2792_p3;

assign ap_return_47 = select_ln376_47_fu_2799_p3;

assign ap_return_48 = select_ln376_48_fu_2806_p3;

assign ap_return_49 = select_ln376_49_fu_2813_p3;

assign ap_return_5 = select_ln376_5_fu_2505_p3;

assign ap_return_50 = select_ln376_50_fu_2820_p3;

assign ap_return_51 = select_ln376_51_fu_2827_p3;

assign ap_return_52 = select_ln376_52_fu_2834_p3;

assign ap_return_53 = select_ln376_53_fu_2841_p3;

assign ap_return_54 = select_ln376_54_fu_2848_p3;

assign ap_return_55 = select_ln376_55_fu_2855_p3;

assign ap_return_56 = select_ln376_56_fu_2862_p3;

assign ap_return_57 = select_ln376_57_fu_2869_p3;

assign ap_return_58 = select_ln376_58_fu_2876_p3;

assign ap_return_59 = select_ln376_59_fu_2883_p3;

assign ap_return_6 = select_ln376_6_fu_2512_p3;

assign ap_return_7 = select_ln376_7_fu_2519_p3;

assign ap_return_8 = select_ln376_8_fu_2526_p3;

assign ap_return_9 = select_ln376_9_fu_2533_p3;

assign beta_buffer_address0 = sext_ln373_fu_1486_p1;

assign icmp_ln369_fu_1475_p2 = (($signed(zext_ln369_fu_1471_p1) < $signed(TM_MIN)) ? 1'b1 : 1'b0);

assign offset_fu_1495_p2 = ($signed(offset_0_reg_1151) + $signed(32'd1));

assign select_ln376_10_fu_2540_p3 = ((write_flag32_0_fu_740[0:0] === 1'b1) ? local_beta_buffer10_0116_fu_732 : local_beta_buffer_10);

assign select_ln376_11_fu_2547_p3 = ((write_flag35_0_fu_728[0:0] === 1'b1) ? local_beta_buffer11_0115_fu_720 : local_beta_buffer_11);

assign select_ln376_12_fu_2554_p3 = ((write_flag38_0_fu_716[0:0] === 1'b1) ? local_beta_buffer12_0113_fu_708 : local_beta_buffer_12);

assign select_ln376_13_fu_2561_p3 = ((write_flag41_0_fu_704[0:0] === 1'b1) ? local_beta_buffer13_0112_fu_696 : local_beta_buffer_13);

assign select_ln376_14_fu_2568_p3 = ((write_flag44_0_fu_692[0:0] === 1'b1) ? local_beta_buffer14_0110_fu_684 : local_beta_buffer_14);

assign select_ln376_15_fu_2575_p3 = ((write_flag48_0_fu_680[0:0] === 1'b1) ? local_beta_buffer155_fu_672 : local_beta_buffer_15);

assign select_ln376_16_fu_2582_p3 = ((write_flag53_0_fu_668[0:0] === 1'b1) ? local_beta_buffer165_fu_660 : local_beta_buffer_16);

assign select_ln376_17_fu_2589_p3 = ((write_flag57_0_fu_656[0:0] === 1'b1) ? local_beta_buffer17_0106_fu_648 : local_beta_buffer_17);

assign select_ln376_18_fu_2596_p3 = ((write_flag60_0_fu_644[0:0] === 1'b1) ? local_beta_buffer18_0104_fu_636 : local_beta_buffer_18);

assign select_ln376_19_fu_2603_p3 = ((write_flag63_0_fu_632[0:0] === 1'b1) ? local_beta_buffer19_0103_fu_624 : local_beta_buffer_19);

assign select_ln376_1_fu_2477_p3 = ((write_flag4_0_fu_580[0:0] === 1'b1) ? local_beta_buffer16_099_fu_592 : local_beta_buffer_1);

assign select_ln376_20_fu_2610_p3 = ((write_flag66_0_fu_620[0:0] === 1'b1) ? local_beta_buffer20_0101_fu_612 : local_beta_buffer_20);

assign select_ln376_21_fu_2617_p3 = ((write_flag69_0_fu_608[0:0] === 1'b1) ? local_beta_buffer21_0100_fu_600 : local_beta_buffer_21);

assign select_ln376_22_fu_2624_p3 = ((write_flag72_0_fu_596[0:0] === 1'b1) ? local_beta_buffer22_098_fu_588 : local_beta_buffer_22);

assign select_ln376_23_fu_2631_p3 = ((write_flag75_0_fu_584[0:0] === 1'b1) ? local_beta_buffer23_097_fu_576 : local_beta_buffer_23);

assign select_ln376_24_fu_2638_p3 = ((write_flag78_0_fu_572[0:0] === 1'b1) ? local_beta_buffer24_095_fu_564 : local_beta_buffer_24);

assign select_ln376_25_fu_2645_p3 = ((write_flag81_0_fu_560[0:0] === 1'b1) ? local_beta_buffer25_094_fu_552 : local_beta_buffer_25);

assign select_ln376_26_fu_2652_p3 = ((write_flag84_0_fu_548[0:0] === 1'b1) ? local_beta_buffer26_061_fu_284 : local_beta_buffer_26);

assign select_ln376_27_fu_2659_p3 = ((write_flag87_0_fu_296[0:0] === 1'b1) ? local_beta_buffer27_064_fu_308 : local_beta_buffer_27);

assign select_ln376_28_fu_2666_p3 = ((write_flag90_0_fu_320[0:0] === 1'b1) ? local_beta_buffer28_067_fu_332 : local_beta_buffer_28);

assign select_ln376_29_fu_2673_p3 = ((write_flag94_0_fu_344[0:0] === 1'b1) ? local_beta_buffer299_fu_356 : local_beta_buffer_29);

assign select_ln376_2_fu_2484_p3 = ((write_flag8_0_fu_604[0:0] === 1'b1) ? local_beta_buffer2_0102_fu_616 : local_beta_buffer_2);

assign select_ln376_30_fu_2680_p3 = ((write_flag98_0_fu_368[0:0] === 1'b1) ? local_beta_buffer30_073_fu_380 : local_beta_buffer_30);

assign select_ln376_31_fu_2687_p3 = ((write_flag101_0_fu_392[0:0] === 1'b1) ? local_beta_buffer31_076_fu_404 : local_beta_buffer_31);

assign select_ln376_32_fu_2694_p3 = ((write_flag104_0_fu_416[0:0] === 1'b1) ? local_beta_buffer32_079_fu_428 : local_beta_buffer_32);

assign select_ln376_33_fu_2701_p3 = ((write_flag107_0_fu_440[0:0] === 1'b1) ? local_beta_buffer33_082_fu_452 : local_beta_buffer_33);

assign select_ln376_34_fu_2708_p3 = ((write_flag110_0_fu_464[0:0] === 1'b1) ? local_beta_buffer34_085_fu_476 : local_beta_buffer_34);

assign select_ln376_35_fu_2715_p3 = ((write_flag113_0_fu_488[0:0] === 1'b1) ? local_beta_buffer35_088_fu_500 : local_beta_buffer_35);

assign select_ln376_36_fu_2722_p3 = ((write_flag116_0_fu_512[0:0] === 1'b1) ? local_beta_buffer36_091_fu_524 : local_beta_buffer_36);

assign select_ln376_37_fu_2729_p3 = ((write_flag119_0_fu_536[0:0] === 1'b1) ? local_beta_buffer37_093_fu_544 : local_beta_buffer_37);

assign select_ln376_38_fu_2736_p3 = ((write_flag122_0_fu_540[0:0] === 1'b1) ? local_beta_buffer38_092_fu_532 : local_beta_buffer_38);

assign select_ln376_39_fu_2743_p3 = ((write_flag125_0_fu_528[0:0] === 1'b1) ? local_beta_buffer39_090_fu_520 : local_beta_buffer_39);

assign select_ln376_3_fu_2491_p3 = ((write_flag11_0_fu_628[0:0] === 1'b1) ? local_beta_buffer3_0105_fu_640 : local_beta_buffer_3);

assign select_ln376_40_fu_2750_p3 = ((write_flag128_0_fu_516[0:0] === 1'b1) ? local_beta_buffer40_089_fu_508 : local_beta_buffer_40);

assign select_ln376_41_fu_2757_p3 = ((write_flag131_0_fu_504[0:0] === 1'b1) ? local_beta_buffer41_087_fu_496 : local_beta_buffer_41);

assign select_ln376_42_fu_2764_p3 = ((write_flag134_0_fu_492[0:0] === 1'b1) ? local_beta_buffer42_086_fu_484 : local_beta_buffer_42);

assign select_ln376_43_fu_2771_p3 = ((write_flag137_0_fu_480[0:0] === 1'b1) ? local_beta_buffer43_084_fu_472 : local_beta_buffer_43);

assign select_ln376_44_fu_2778_p3 = ((write_flag140_0_fu_468[0:0] === 1'b1) ? local_beta_buffer44_083_fu_460 : local_beta_buffer_44);

assign select_ln376_45_fu_2785_p3 = ((write_flag143_0_fu_456[0:0] === 1'b1) ? local_beta_buffer45_081_fu_448 : local_beta_buffer_45);

assign select_ln376_46_fu_2792_p3 = ((write_flag146_0_fu_444[0:0] === 1'b1) ? local_beta_buffer46_080_fu_436 : local_beta_buffer_46);

assign select_ln376_47_fu_2799_p3 = ((write_flag149_0_fu_432[0:0] === 1'b1) ? local_beta_buffer47_078_fu_424 : local_beta_buffer_47);

assign select_ln376_48_fu_2806_p3 = ((write_flag152_0_fu_420[0:0] === 1'b1) ? local_beta_buffer48_077_fu_412 : local_beta_buffer_48);

assign select_ln376_49_fu_2813_p3 = ((write_flag155_0_fu_408[0:0] === 1'b1) ? local_beta_buffer49_075_fu_400 : local_beta_buffer_49);

assign select_ln376_4_fu_2498_p3 = ((write_flag14_0_fu_652[0:0] === 1'b1) ? local_beta_buffer4_0108_fu_664 : local_beta_buffer_4);

assign select_ln376_50_fu_2820_p3 = ((write_flag158_0_fu_396[0:0] === 1'b1) ? local_beta_buffer50_074_fu_388 : local_beta_buffer_50);

assign select_ln376_51_fu_2827_p3 = ((write_flag161_0_fu_384[0:0] === 1'b1) ? local_beta_buffer51_072_fu_376 : local_beta_buffer_51);

assign select_ln376_52_fu_2834_p3 = ((write_flag164_0_fu_372[0:0] === 1'b1) ? local_beta_buffer52_071_fu_364 : local_beta_buffer_52);

assign select_ln376_53_fu_2841_p3 = ((write_flag167_0_fu_360[0:0] === 1'b1) ? local_beta_buffer53_069_fu_352 : local_beta_buffer_53);

assign select_ln376_54_fu_2848_p3 = ((write_flag170_0_fu_348[0:0] === 1'b1) ? local_beta_buffer54_068_fu_340 : local_beta_buffer_54);

assign select_ln376_55_fu_2855_p3 = ((write_flag173_0_fu_336[0:0] === 1'b1) ? local_beta_buffer55_066_fu_328 : local_beta_buffer_55);

assign select_ln376_56_fu_2862_p3 = ((write_flag176_0_fu_324[0:0] === 1'b1) ? local_beta_buffer56_065_fu_316 : local_beta_buffer_56);

assign select_ln376_57_fu_2869_p3 = ((write_flag179_0_fu_312[0:0] === 1'b1) ? local_beta_buffer57_063_fu_304 : local_beta_buffer_57);

assign select_ln376_58_fu_2876_p3 = ((write_flag182_0_fu_300[0:0] === 1'b1) ? local_beta_buffer58_062_fu_292 : local_beta_buffer_58);

assign select_ln376_59_fu_2883_p3 = ((write_flag185_0_fu_288[0:0] === 1'b1) ? local_beta_buffer59_060_fu_280 : local_beta_buffer_59);

assign select_ln376_5_fu_2505_p3 = ((write_flag17_0_fu_676[0:0] === 1'b1) ? local_beta_buffer5_0111_fu_688 : local_beta_buffer_5);

assign select_ln376_6_fu_2512_p3 = ((write_flag20_0_fu_700[0:0] === 1'b1) ? local_beta_buffer6_0114_fu_712 : local_beta_buffer_6);

assign select_ln376_7_fu_2519_p3 = ((write_flag23_0_fu_724[0:0] === 1'b1) ? local_beta_buffer7_0117_fu_736 : local_beta_buffer_7);

assign select_ln376_8_fu_2526_p3 = ((write_flag26_0_fu_748[0:0] === 1'b1) ? local_beta_buffer8_0119_fu_756 : local_beta_buffer_8);

assign select_ln376_9_fu_2533_p3 = ((write_flag29_0_fu_752[0:0] === 1'b1) ? local_beta_buffer9_0118_fu_744 : local_beta_buffer_9);

assign select_ln376_fu_2470_p3 = ((write_flag_0_fu_556[0:0] === 1'b1) ? local_beta_buffer_096_fu_568 : local_beta_buffer_0);

assign sext_ln373_1_fu_1501_p1 = $signed(beta_buffer_q0);

assign sext_ln373_fu_1486_p1 = offset_0_reg_1151;

assign shl_ln373_fu_1505_p2 = sext_ln373_1_fu_1501_p1 << InterSubBeta;

assign tm_fu_1480_p2 = (tm_0_reg_1160 + 16'd1);

assign trunc_ln373_fu_1491_p1 = tm_0_reg_1160[5:0];

assign zext_ln369_fu_1471_p1 = tm_0_reg_1160;

endmodule //copy_local_beta
